# Generated by Django 4.1.4 on 2022-12-24 17:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(default=807623, primary_key=True, serialize=False)),
                ('username', models.CharField(default='Anonymous User', max_length=50)),
                ('caption', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(default='4c50870fef410d14ff495ea1f532565a.jpg', null=True, upload_to='post/photo')),
                ('comment', models.CharField(max_length=300, null=True)),
                ('no_of_likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(null=True)),
                ('bio', models.CharField(max_length=300, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='media/images')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
