# Generated by Django 4.1.4 on 2022-12-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(default=226230, primary_key=True, serialize=False),
        ),
    ]
