# Generated by Django 4.1.4 on 2022-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsapp', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(null=True),
        ),
    ]
