# Generated by Django 4.1.4 on 2022-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsapp', '0014_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
