# Generated by Django 4.1.4 on 2022-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsapp', '0015_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
