# Generated by Django 4.1.4 on 2022-12-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsapp', '0017_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
